### ISSUE TITLE
Add search bar on the main screen 

### ISSUE THREAD

**Issue by aarish21** [aarish21/OnTrack#2]
Add search bar on the main screen so that we can search for the required series from anywhere

**Comment by InsanelyHarsh** [comment]
I would like to take on this task.

**Comment by aarish21** [comment]
> I would like to take on this task.

ok @InsanelyHarsh

**Comment by InsanelyHarsh** [comment]
Hi @aarish21,
Do I have to add a Search bar for searching or do I have to add navigation to that movie/anime/manga/book?

**Comment by InsanelyHarsh** [comment]
And what will be the minimum deployment target?
Are you good with iOS 16?

**Comment by aarish21** [comment]
@InsanelyHarsh you need to add search bar for searching from main screen

**Comment by aarish21** [comment]
> And what will be the minimum deployment target?
> Are you good with iOS 16?

15 is fine

**Comment by InsanelyHarsh** [comment]
I think the issue is due to a different version of Xcode. 
Let me check on Xcode 13 and the iOS 15 Simulator.

> > And what will be the minimum deployment target?
> > Are you good with iOS 16?
> 
> 15 is fine

**Comment by aarish21** [comment]
> I think the issue is due to a different version of Xcode. Let me check on Xcode 13 and the iOS 15 Simulator.
> 
> > > And what will be the minimum deployment target?
> > > Are you good with iOS 16?
> > 
> > 
> > 15 is fine

ok

**Comment by aarish21** [comment]
resolved by @InsanelyHarsh
